# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    environment:
      GO111MODULE: on

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      # specify any bash command here prefixed with `run: `
      - run: 
          name: Run tests
          command: make ci
